[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn wsgi:app"
healthcheckPath = "/"
healthcheckTimeout = 100

[build.env]
PYTHON_VERSION = "3.9"